configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/grid%2Fspreadsheet-api-8f089189d87fe061afe62a54cdce6752e1b9597de7fdaa4154412ce2115c7ed4.yml
openapi_spec_hash: 2bff1feefeadafaa3c714059c1ebf682
config_hash: 3e61a9566953ce5dbd4bcea7ceb568a3
